name: Update Remote Translations

on:
  push:
    branches:
      - main

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/deps
      - name: Update Remote Translations
        run: node bin/translations/translations-push.js
      - name: Send Slack notification
        if: failure()
        uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_MAIN_TECH }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: *Update Failed:* Translations could not be updated on locize. Please check the GitHub Actions logs for more details."
                  }
                }
              ]
            }
